"""empty message

Revision ID: 6f1edea5c69d
Revises: 4d200ff0931a
Create Date: 2020-04-10 21:26:56.575637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f1edea5c69d'
down_revision = '4d200ff0931a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('actors', sa.Column('gender', sa.String(), nullable=True))
    op.drop_column('actors', 'genres')
    op.drop_column('actors', 'role')
    op.add_column('movies', sa.Column('release_date', sa.Date(), nullable=True))
    op.drop_column('movies', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('genres', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('movies', 'release_date')
    op.add_column('actors', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('actors', sa.Column('genres', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('actors', 'gender')
    op.drop_column('actors', 'age')
    # ### end Alembic commands ###
